before_script:
  - apt-get update -qq
  - apt-get install -qq git
  - 'which ssh-agent || ( apt-get install -qq openssh-client )'
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY" | base64 -d)
  - mkdir -p ~/.ssh
  - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config

deploy_server1:
  stage: deploy
  environment:
    name: server1
    url: $SERVER1
  script:
    - ssh $SSH_USER@$SERVER1 "sudo rm -rf /var/www/app &&
      cd /var/www &&
      git clone git@gitlab.com:mkhramov/dbanalytics-backend.git app &&
      sudo chown www-data:www-data app -R &&
      cd app &&
      sh ./deploy/deploy.sh $SERVER1 $DATABASE_HOST $DATABASE_USER $DATABASE_PASSWORD $DATABASE_NAME $RABBITMQ_HOST $RABBITMQ_USER $RABBITMQ_PASSWORD"
  only:
    - main

test_server2:
  stage: test
  environment:
    name: server2
    url: $SERVER2
  script:
    - ssh $SSH_USER@$SERVER2 "sudo rm -rf /var/www/app &&
      cd /var/www &&
      git clone git@gitlab.com:mkhramov/dbanalytics-backend.git app &&
      sudo chown www-data:www-data app -R &&
      cd app &&
      sh ./deploy/test.sh $SERVER1 $DATABASE_HOST $DATABASE_USER $DATABASE_PASSWORD $DATABASE_NAME"
  only:
    - main
